---
plugins:
  ekklesia_enabled:
    default: true
    client: true

  ekklesia_auto_group:
    client: true

  ekklesia_auto_trust_level:
    default: 1
    client: true

  ekklesia_login_button_title:
    default: "with Ekklesia"
    client: true

