---
plugins:
  ekklesia_enabled:
    default: true
    client: true

  ekklesia_auto_group:
    client: true
    default: ekklesia

  ekklesia_auto_trust_level_guest:
    default: 0
    client: true

  ekklesia_auto_trust_level_plain_member:
    default: 1
    client: true

  ekklesia_auto_trust_level_eligible_member:
    default: 2
    client: true

  ekklesia_auto_trust_level_system_user:
    default: 4
    client: true

  ekklesia_login_button_title:
    default: "with Ekklesia"
    client: true

  ekklesia_client_id:
    default: "discourse"
    client: true

  ekklesia_client_secret:
    client: true
    default: ekklesia_secret

  ekklesia_site_url:
    client: true
    default: https://ekklesia_id_server
